-- Drop tables if they exist
DROP TABLE IF EXISTS AERENDE_ANT;
DROP TABLE IF EXISTS LOG;
DROP TABLE IF EXISTS AERENDE;
DROP TABLE IF EXISTS DOSSIEPLAN;
DROP TABLE IF EXISTS HANDLAEGGARE;
DROP TABLE IF EXISTS ENHET;
DROP TABLE IF EXISTS REG;


CREATE TABLE REG (
    REG_ID TEXT PRIMARY KEY,
    REG_NAMN TEXT NOT NULL
);


CREATE TABLE DOSSIEPLAN (
    DOSS_NR INTEGER PRIMARY KEY,
    NAMN TEXT NOT NULL
);


CREATE TABLE HANDLAEGGARE (
    HAND_ID TEXT PRIMARY KEY,
    HAND_NAMN TEXT NOT NULL
);


CREATE TABLE ENHET (
    ENHT_KOD TEXT PRIMARY KEY,
    ENHT_NAMN TEXT NOT NULL
);


CREATE TABLE AERENDE (
    DNR INTEGER PRIMARY KEY,
    REG_ID TEXT NOT NULL,
    IN_UT TEXT,
    DOSS_NR INTEGER,
    HAND_ID TEXT,
    ENHT_KOD TEXT,
    INKUPP DATE,
    REGDAT DATE,
    AVSDAT DATE,
    STAT TEXT,
    ATEXT TEXT,
    MOTPART_BET TEXT,
    FRAN_TILL TEXT,
    FOREIGN KEY (REG_ID) REFERENCES REG (REG_ID),
    FOREIGN KEY (DOSS_NR) REFERENCES DOSSIEPLAN (DOSS_NR),
    FOREIGN KEY (HAND_ID) REFERENCES HANDLAEGGARE (HAND_ID),
    FOREIGN KEY (ENHT_KOD) REFERENCES ENHET (ENHT_KOD)
);


CREATE TABLE AERENDE_ANT (
    DNR INTEGER,
    LNR INTEGER,
    IN_UT TEXT,
    ANT_TEXT TEXT,
    REG_ID TEXT,
    DATUMIN DATE,
    DATUMUT DATE,
    ANMKAL TEXT,
    HAND_ID TEXT,
    AVSMOT TEXT,
    PRIMARY KEY (DNR, LNR),
    FOREIGN KEY (DNR) REFERENCES AERENDE (DNR),
    FOREIGN KEY (REG_ID) REFERENCES REG (REG_ID),
    FOREIGN KEY (HAND_ID) REFERENCES HANDLAEGGARE (HAND_ID)
);


CREATE TABLE LOG (
    DNR INTEGER,
    REG_ID TEXT,
    LOGDAT DATE,
    LOGFLT TEXT,
    PRIMARY KEY (DNR, REG_ID, LOGDAT),
    FOREIGN KEY (DNR) REFERENCES AERENDE (DNR),
    FOREIGN KEY (REG_ID) REFERENCES REG (REG_ID)
);
